-- SXG Complete v4 Upgrade: GPS, Admin-Live-Tracking, Push, Lohn, Prämien, Fahrpläne, Chat, AU Upload
alter table profiles add column if not exists guard_id text;
alter table profiles add column if not exists tax_id text;
alter table profiles add column if not exists address text;
alter table profiles add column if not exists emergency_contact text;
alter table profiles add column if not exists qualification text;
alter table profiles add column if not exists iban text;
alter table profiles add column if not exists hourly_rate numeric default 0;
alter table jobs add column if not exists address text;
alter table jobs add column if not exists lat numeric;
alter table jobs add column if not exists lng numeric;
alter table jobs add column if not exists geo_radius_m integer default 1000;
alter table jobs add column if not exists start_date date;
alter table jobs add column if not exists end_date date;
alter table jobs add column if not exists status text default 'open';
alter table jobs add column if not exists updated_at timestamptz default now();
update jobs set start_date = job_date where start_date is null;
update jobs set end_date = job_date where end_date is null;
alter table job_assignments add column if not exists profile_id uuid references profiles(id);
alter table job_assignments add column if not exists created_at timestamptz default now();
update job_assignments set profile_id = employee_id where profile_id is null;
alter table attendance add column if not exists profile_id uuid references profiles(id);
alter table attendance add column if not exists job_id bigint references jobs(id);
alter table attendance add column if not exists check_in timestamptz;
alter table attendance add column if not exists check_out timestamptz;
alter table attendance add column if not exists clock_in timestamptz;
alter table attendance add column if not exists clock_out timestamptz;
alter table attendance add column if not exists lat numeric;
alter table attendance add column if not exists lng numeric;
alter table attendance add column if not exists present boolean default true;
alter table timesheets add column if not exists profile_id uuid references profiles(id);
alter table timesheets add column if not exists work_date date;
alter table timesheets add column if not exists start_time text;
alter table timesheets add column if not exists end_time text;
alter table timesheets add column if not exists break_minutes integer default 0;
alter table timesheets add column if not exists location text;
alter table timesheets add column if not exists activity text;
alter table timesheets add column if not exists description text;
alter table timesheets add column if not exists hours_worked numeric;
alter table timesheets add column if not exists approved boolean default false;
update timesheets set profile_id = employee_id where profile_id is null;
update timesheets set hours_worked = hours where hours_worked is null;
alter table leave_requests add column if not exists profile_id uuid references profiles(id);
alter table leave_requests add column if not exists leave_type text;
alter table leave_requests add column if not exists approved boolean default false;
alter table leave_requests add column if not exists reviewed_by uuid references profiles(id);
alter table leave_requests add column if not exists reviewed_at timestamptz;
alter table leave_requests add column if not exists au_file_path text;
update leave_requests set profile_id = employee_id where profile_id is null;
update leave_requests set leave_type = type where leave_type is null;
create table if not exists payroll_documents (id bigint generated always as identity primary key, profile_id uuid references profiles(id) on delete cascade, title text, month text, file_path text, file_name text, uploaded_by uuid references profiles(id), created_at timestamptz default now());
create table if not exists location_logs (id bigint generated always as identity primary key, profile_id uuid references profiles(id) on delete cascade, job_id bigint references jobs(id) on delete cascade, lat numeric, lng numeric, accuracy numeric, created_at timestamptz default now());
create table if not exists bonuses (id bigint generated always as identity primary key, profile_id uuid references profiles(id) on delete cascade, amount numeric not null default 0, reason text, created_by uuid references profiles(id), created_at timestamptz default now());
create table if not exists route_plans (id bigint generated always as identity primary key, job_id bigint references jobs(id) on delete cascade, driver_profile_id uuid references profiles(id), passenger_profile_ids uuid[] default '{}', meeting_time text, meeting_point text, notes text, created_by uuid references profiles(id), created_at timestamptz default now(), updated_at timestamptz default now());
create table if not exists chat_messages (id bigint generated always as identity primary key, from_profile_id uuid references profiles(id) on delete cascade, to_profile_id uuid references profiles(id) on delete cascade, body text, created_at timestamptz default now());
create table if not exists push_subscriptions (id bigint generated always as identity primary key, profile_id uuid references profiles(id) on delete cascade, endpoint text unique not null, p256dh text not null, auth text not null, created_at timestamptz default now());
insert into storage.buckets (id,name,public) values ('payslips','payslips',false) on conflict(id) do nothing;
do $$ declare t text; begin foreach t in array array['profiles','jobs','job_assignments','attendance','timesheets','leave_requests','payroll_documents','location_logs','bonuses','route_plans','chat_messages','push_subscriptions'] loop execute format('alter table %I enable row level security', t); execute format('drop policy if exists "sxg read all" on %I', t); execute format('drop policy if exists "sxg insert all" on %I', t); execute format('drop policy if exists "sxg update all" on %I', t); execute format('drop policy if exists "sxg delete all" on %I', t); execute format('create policy "sxg read all" on %I for select using (true)', t); execute format('create policy "sxg insert all" on %I for insert with check (true)', t); execute format('create policy "sxg update all" on %I for update using (true) with check (true)', t); execute format('create policy "sxg delete all" on %I for delete using (true)', t); end loop; end $$;
drop policy if exists "payslips read" on storage.objects;
drop policy if exists "payslips insert" on storage.objects;
create policy "payslips read" on storage.objects for select using (bucket_id='payslips');
create policy "payslips insert" on storage.objects for insert with check (bucket_id='payslips');
